2019-03-03 10:08:18,115 ERROR: Exception on /home [GET] [in /home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/siddharth/Desktop/FutureIn/app/routes.py", line 79, in home
    return render_template('home.html')
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/siddharth/Desktop/FutureIn/app/templates/home.html", line 11, in template
    <link rel="stylesheet" href="{{ url_for('static', filename='css/open-iconic-bootstrap.min.css' }}">
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 785, in parse_call
    value = self.parse_expression()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/parser.py", line 564, in parse_primary
    next(self.stream)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "/home/siddharth/Desktop/FutureIn/venv/lib/python3.6/site-packages/jinja2/lexer.py", line 690, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2019-03-03 11:57:37,051 INFO: Microblog startup [in D:\My Books\SIH2019\FutureIn2\app\__init__.py:52]
2019-03-03 12:00:56,406 INFO: Microblog startup [in D:\My Books\SIH2019\FutureIn2\app\__init__.py:52]
2019-03-03 12:03:28,516 INFO: Microblog startup [in D:\My Books\SIH2019\FutureIn2\app\__init__.py:52]
2019-03-03 12:09:41,102 INFO: Microblog startup [in D:\My Books\SIH2019\FutureIn2\app\__init__.py:52]
2019-03-03 12:12:57,334 INFO: Microblog startup [in D:\My Books\SIH2019\FutureIn2\app\__init__.py:52]
2019-03-03 12:17:18,651 INFO: Microblog startup [in D:\My Books\SIH2019\FutureIn2\app\__init__.py:52]
2019-03-03 12:17:24,633 ERROR: Exception on / [GET] [in d:\program_files\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\program_files\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\program_files\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\program_files\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\program_files\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\program_files\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\program_files\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\My Books\SIH2019\FutureIn2\app\routes.py", line 40, in index
    posts = current_user.followed_posts().paginate(
  File "d:\program_files\python\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'followed_posts'
